upgrade github actions plugins
the build failed with

```
Download action repository 'actions/upload-pages-artifact@v1' (SHA:84bb4cd4b733d5c320c9c9cfbc354937524f4d64)
Getting action download info
Error: Missing download info for actions/upload-artifact@v3
```
https://github.com/joernio/website/actions/runs/13837373766/job/38715747694

upload-artifact@v3 is deprecated (see
https://github.com/marketplace/actions/upload-a-build-artifact).
We don't use it directory, but I guess it's used by
`upload-pages-artifact` - so trying to update that one...